### ISSUE TITLE
Studio Configuration

### ISSUE THREAD

**Issue by pedrooa** [TwilioLatamEngHub/plugin-conversations-outbound-whatsapp#2]
How should my studio be configured in order for the task to be initiated with the appropriate worker when the 'route reply back to me' option is selected?

![Screen Shot 2023-01-10 at 14 34 40](https://user-images.githubusercontent.com/26471690/211622321-ff094678-8e07-4faa-9c5c-ab949cbd2668.png)
![Screen Shot 2023-01-10 at 14 34 35](https://user-images.githubusercontent.com/26471690/211622330-6f424a14-e692-4cce-9d48-60a2195828ac.png)

This is my configuration, and everything works as expected, except for the 'reply back to me' option.

Thanks :)

**Comment by chouputra** [comment]
In the send to flex widget set attributes to:

{"KnowAgentRoutingFlag": "{{trigger.conversation.ChannelAttributes.KnownAgentRoutingFlag}}","KnownAgentWorkerFriendlyName": "{{trigger.conversation.ChannelAttributes.KnownAgentWorkerFriendlyName}}"}

In your workflow make sure you assign to to worker based on task.KnownAgentWorkerFriendlyName againts the worker friendly name.

**Comment by pedrooa** [comment]
Thanks @chouputra ! Got it to work :)
